[project]
name = "ammoseekr"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.0",
]

[tool.ruff.lint]
select = ["F", "B", "E", "SIM"]
ignore = ["E501"]
fixable = ["ALL"]
